FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04
MAINTAINER Ilya Trofimov
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -yqq update
RUN apt-get -yqq install git cmake vim wget psmisc

#
# Conda
#
RUN wget https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh
RUN chmod 777 ./Anaconda3-2022.10-Linux-x86_64.sh
RUN bash ./Anaconda3-2022.10-Linux-x86_64.sh -b -p /home/anaconda
ENV PATH="/home/anaconda/bin:$PATH"

EXPOSE 8895
EXPOSE 8896
RUN echo "(jupyter notebook --ip=0.0.0.0 --port 8895 --allow-root &)" > start_jupyter.sh
CMD ["/bin/bash"]
